version: '3.3'
services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node_1
    entrypoint:
      - /bin/sh
      - build/dev.build.sh
    ports:
      - 3001:3001
      - 4321:4321
    working_dir: /app
    volumes:
      - .:/app:cached